### ISSUE TITLE
`filter` Action method should behave like Array.prototype.filter

### ISSUE THREAD

**Issue by Chaphasilor** [rivalis/rivalis-core#11]
From the documentation [here](https://rivalis.io/docs/actions), specifically the code snippet, it looks like an actor is filtered **out** from a broadcast if the `filter` method returns `true`.

However, normally in JS, for example with the `Array.prototype.filter` method, if the callback returns `true` the element is **included**, and it is excluded (filtered out) if the CB returns `false`.

I don't see a reason why Rivalis should do this the other way around. Maybe it's just a typo in the docs, I haven't tested it yet :)

**Comment by kalevski** [comment]
Thanks for the suggestion.
The filter implementation will be changed to work in same way as Array.prototype.filter
I agree with you that Rivalis needs to follow JS standard.
